### ISSUE TITLE
hi need help about anime addons including this addons

### ISSUE THREAD

**Issue by daniel-ntl** [DxCx/plugin.video.animeram#7]
hi, i'm daniel, i'm still using kodi jarvis 16.1, because my android box is android 4.2.2,  i already install animeram 0.0.6 not working,  i notice that your animeram addon can only be played in kodi krypton, please sir, make animeram that works in kodi jarvis 16.1, thx alot

**Comment by DxCx** [comment]
hey @daniel-ntl,
animeram is deprecated those days, and im mostly using (and maintaining) 9anime instead.
https://github.com/DxCx/plugin.video.9anime

However, it requires Kodi 17.0+ because of unsupported Kodi features that needed to make it work.
same here for animeram btw, kodi restriction is not because i wanted to but because of missing features.
